### ISSUE TITLE
The linkhttp://hls.ucsd.edu/ is not reachable

### ISSUE THREAD

**Issue by Paebbels** [KastnerRG/pp4fpgas#2]
The link http://hls.ucsd.edu is broken.

> ERR_CONNECTION_TIMED_OUT

**Comment by Paebbels** [comment]
This happens with http://kastner.ucsd.edu/ too.

**Comment by rck289** [comment]
Yes, some security issues with the machine that is hosting my website. It will hopefully be up and running in a few days.

**Comment by Paebbels** [comment]
Sorry, but this issue is not fixed yet, thus it can not be closed yet. It would communicate fase truth.

(My close/reopen operation was a mistake due to a bad road :) )
