### ISSUE TITLE
Redundant condition in while loop  (Figure 10.2) ?

### ISSUE THREAD

**Issue by L30nardoSV** [KastnerRG/pp4fpgas#23]
Hi, 

Is there any reason why  `j > 0` is evaluated twice in the following ?

https://github.com/KastnerRG/pp4fpgas/blob/master/examples/insertion_sort.cpp#L9

**Comment by rck289** [comment]
We wanted to be extra sure that j > 0 :) 
Fixed it. Thanks for your careful reading!
