### ISSUE TITLE
Possible wrong variable name in text of Section 10.2.1

### ISSUE THREAD

**Issue by L30nardoSV** [KastnerRG/pp4fpgas#24]
The paragraph in https://github.com/KastnerRG/pp4fpgas/blob/master/sorting.tex#L71 refers to the code snippet in Figure 10.2.

Specifically, the text uses the `index` term. However, by looking at the code, it seems the actual name of the referred variable is `item` instead.

**Comment by rck289** [comment]
Fixed. Thanks for your careful reading!
