### ISSUE TITLE
Index out of range possible in merge program

### ISSUE THREAD

**Issue by j1s1e1** [KastnerRG/pp4fpgas#3]
The merge sort program here:

pp4fpgas/examples/merge_sort.cpp

has the following test statement that can fail:

if((f1 < i2 && in[f1] <= in[f2]) || f2 == i3)

When f2 == i3, the in[f2] test fails for array index out of range.  The code appears to work if the in[f2] test is separated and not performed when the values are equal.

**Comment by stephenneuendorffer** [comment]
Thanks for pointing this out.  I've updated the code to avoid it.
