### ISSUE TITLE
The missing files in the examples folder

### ISSUE THREAD

**Issue by vickyiii** [KastnerRG/pp4fpgas#4]
Hi Kastner，
     Recently, I'm working with the FFT Project using the baseline code in the book ,but I couldn't find the exact "fft_stage_one", "fft_stage_two" and "fft_stage_three" function files mentioned in the "fft_stages.cpp" file in the examples folder.
     My partner is working with the CORDIC Project. There is a top file included in the "cordic.c" file called "cordic.h" which is not included in the examples folder also.
     Would you please help us with this issue?
     Thank you so much.

**Comment by stephenneuendorffer** [comment]
Good point.  I'll get them added.

**Comment by stephenneuendorffer** [comment]
I've updated the code and restructured some of the adjacent text.  Hope this helps!
